### PR TITLE
Logo

### PR DESCRIPTION
**Pull request by sparalic**
@datapythonista, I wanted to incorporate the global diversity of the team, and this was the best I could find. Let me know what you think!

### CODE REVIEW

**Comment by datapythonista** [comment]
Good job, thank about this! You'll have to fix the conflicts, and also, you committed a `.DS_Store` file to the repository, that you may want to delete.

**Comment by datapythonista** [comment]
Thanks @sparalic, getting there. Couple of things. If you can have a look at https://github.com/python-sprints/pandas-mentoring/pull/25/files, looks like there is some stuff from the conflict you've got.

Also, if you want, I think to include an image in markdown, you can use ``.

Thanks!

**Comment by datapythonista** [comment]
Once you're done, you check the diff of the PR (or locally with `git diff upstream/master`), and make sure that you only have the intended changes.

**Comment by sparalic** [comment]
@datapythonista  Thanks! I finally fixed the conflict. I used ``, but I wasn't sure it could adjust the image dimensions. So I went with ``

**Comment by datapythonista** [comment]
That makes sense, thank you!

@martinagvilas @galuhsahid @dujm do you mind reviewing this, and approve/merge when you're happy? Thanks!

**Review by sparalic — COMMENTED** [review]
Everything seems okay

**Review by dujm — APPROVED** [review]

**Pull request merged**
