### PR TITLE
add username

### PR DESCRIPTION
**Pull request by dujm**
made changes to the README file from my forked repo :)

### CODE REVIEW

**Comment by datapythonista** [comment]
Cool, good job. Do you mind in a separate PR, make the word `pandas` in `This is the list of the [GitHub](https://github.com) usernames of all the people interested in contributing to pandas:` a link to the pandas repository please?

Thanks!

**Comment by dujm** [comment]
Hi Marc, I sent a new PR from a new branch. Is this the right way to split pull requests? Would you recommend creating small PRs rather than large PRs when people work together?

**Comment by datapythonista** [comment]
Thanks @dujm, I see you know what you're doing already. :)

Yes, I think small PRs are always better (without going crazy of course). And also, in projects like pandas, we don't merge unrelated things together in the same PR. One of the main reasons, besides keeping things simple, is that we want to be able to revert changes that cause trouble (that happens rarely, but it happens), and we don't want to revert unrelated changes with that.

I think this has been the right way to split PRs. Most people sent the first PR from master, and I was asking for a second PR for them to see the value in working with branches, and I was distracted and didn't realize you already did. :) Only tip is that you probably want to name branches with more descriptive names, you may end up having many in the future.

Great job! Feel free to review other people's PR.

**Comment by dujm** [comment]
Thanks for the detailed explanation @datapythonista. I agree, splitting PRs and using descriptive branch names totally make sense for a big open-source project :) 

Ok. I will go head with reviewing other PRs.

**Pull request merged**
