### PR TITLE
Add dorothykiz1 to file

### PR DESCRIPTION
**Pull request by dorothykiz1**

### CODE REVIEW

**Comment by datapythonista** [comment]
Thanks @dorothykiz1, great job. Before I merge this, do you mind adding a subtitle to this page, so all the content is under a section `Participants` (we'll add more sections later). But don't do it in this PR, open a separate one please (it's not trivial to do it, ask help when you need to).

**Comment by dorothykiz1** [comment]
Hello Marc ,i see i have conflicts do i need o merge to the master before the second pull request

**Comment by datapythonista** [comment]
I resolved the conflicts for you. You'll have another conflict later you'll have to fix, so don't worry about it. ;)

But now the challenge is to have two different PRs with the two independent changes. And it's not easy. Give it a try, and let us know if you have problems you can't solve yourself.

**Comment by datapythonista** [comment]
Ok, saw your other PR now, merging this. You can fix the conflicts in that one :)

**Pull request merged**
