### PR TITLE
Basic hello world pipeline

### PR DESCRIPTION
**Pull request by bhavaniravi**
1. The starting point of issue #32 
2. Though we have the full setup in #107, we will split it into a bunch of PRs finally getting to the end pipeline
3. [You can try and set up an azure pipeline for your forked repo](https://www.azuredevopslabs.com/labs/azuredevops/github-integration/)

### CODE REVIEW

**Review by dujm — APPROVED** [review]

**Review by datapythonista — CHANGES_REQUESTED** [review]
Looks great!

Marking it as `Request changes`, and this should prevent anyone from merging it. But no actual changes requested, just want this open until most people has been able to check the PR and the CI build.

I see that the CI build is still private, at least is requesting login to me. Can you have a look and make it public. Would be very useful if people can see the details of the build.

Thanks a lot for working on this.

**Comment by sara-02** [comment]
> Marking it as `Request changes`, and this should prevent anyone from merging it. 

Have a question here, the merge pull request tab is green for me. Shouldn't it be grey, since changes have been requested?

**Comment by sara-02** [comment]
+1 to making the view public, not able to view pipelines or errors(if any)

**Comment by datapythonista** [comment]
> Have a question here, the merge pull request tab is green for me. Shouldn't it be grey, since changes have been requested?

Good point. I think it's grey when the CI is red, and disabled when GitHub is set up to enforce a minimum number of approvals. But by convention (in pandas, and I'd say common sense), if someone request changes to a PR, the PR shouldn't be merged until that person is happy and changes the review. Otherwise the request changes is somehow pointless, and I could just add a comment requesting the changes.

**Comment by bhavaniravi** [comment]
@datapythonista `Request Changes` is more of repo settings over CI set up right? I think I did that. Also, the azure project is public now

**Comment by datapythonista** [comment]
Thanks @bhavaniravi, I can access azure now, and looks like the setting causes actually that the PR can't be merged when there are changes requested. Not sure if we want that, may be you can create an issue to discuss? But it's great to know that there is an option for it.

Thanks!

**Comment by Ayowolet** [comment]
So how do I access the azure project? I have attempted to set up one with my forked repo but I think I have to access the one @bhavaniravi created.

**Comment by datapythonista** [comment]
good question @Ayowolet. For the main repo (https://github.com/python-sprints/pandas-mentoring) it only makes sense to have on azure pipelines account. Using @bhavaniravi is enough (in a different kind of project we would probably want to have a shared account, but for what we are doing I think it's good enough).

Since the goal here is learning, I think it'd be very useful that everybody interested set up an instance in their forks. This won't be particularly useful in terms of running the jobs, but I think it'll be great to understand better how CI systems work, and be able to deal with them better when we get to more complex configurations like the one in pandas.

**Comment by sparalic** [comment]
@datapythonista I agree. @Ayowolet I forked the demo repo from this link Marc provided earlier and followed the lab, to get a better understanding of how CI works. 

https://www.azuredevopslabs.com/labs/azuredevops/github-integration/

**Review by datapythonista — APPROVED** [review]
It's been almost a week, I think it's time to move forward for the CI, and start implementing the whole system. Hopefully everybody had a look at this.

Merge when ready @bhavaniravi, thanks for the patience.

**Comment by bhavaniravi** [comment]
Cool. I'm on it. 

@datapythonista should I merge and create a new PR or update the changes in the same branch?

**Pull request merged**
