### PR TITLE
Add Github Link

### PR DESCRIPTION
**Pull request by Ayowolet**

### CODE REVIEW

**Comment by datapythonista** [comment]
Amazing work @Ayowolet, both PRs are perfect now. :)

**Comment by Ayowolet** [comment]
Thank you Marc.

I'm trying to update my fork with the latest changes. Is it okay to create
a pull request that merges to my 'master' or do I need to create a branch
for this?

**Comment by datapythonista** [comment]
The master in your github fork is irrelevant, it's very rare that you care about it, and you can leave it outdated.

To update your local master, so you're able to create new branches and work in new PRs, you can do this:
```
git checkout master
git fetch upstream
git merge upstream/master
```
The order of the two first commands is irrelevant. And this assumes you have a remote named `upstream` that points to the original repo.

Does this make sense?

**Comment by Ayowolet** [comment]
Yes, it makes sense. I've updated it now.

Thank you very much for answering my questions.

**Comment by datapythonista** [comment]
Great! I gave you commit access to the repo, feel free to review other people PRs, help them, and merge when you're happy.

**Comment by Ayowolet** [comment]
Oh wow! Okay,  I will do that. Thank you.

**Pull request merged**
