### PR TITLE
Revert "Add participants subtitle to README.md"

### PR DESCRIPTION
**Pull request by martinagvilas**
Oops, I merged but realized there is a typo in Participants: its says instead partipants

### CODE REVIEW

**Review by datapythonista — COMMENTED** [review]
Why do you prefer to revert the commit, instead of just fixing the typo?

**Comment by martinagvilas** [comment]
This is a good question. What is considered best practice? In this case it is a very small change that I would have to make to revert the typo, so fixing it with another PR would make sense. But if I would have merged a more complicated PR by error it would be easier to just revert the merge right?

**Comment by dorothykiz1** [comment]
Alright have just noticed the typo too.

**Comment by datapythonista** [comment]
Not sure what is considered a good practice. But in pandas, probably half of the PRs I opened had something that had to be changed, and in all the cases we applied the fix in a follow up, and never reverted.

I'd say reverting is only used when you break something, and the fix is not obvious or fast. If we introduce a bug in pandas in a PR, and what to fix requires discussion, or we're even unsure that the PR was a good idea, then we'd revert. Otherwise we just fix the problem and move forward.

Probably worth mentioning that in pandas and open source in general there is a 0 blame policy. We always focus on the solutions, and not on the problem. At least in a personal level, we may discuss about the problem if it's because we don't have enough tests, they're not running properly... So we can also focus on the solution to the root cause of the problem.

**Pull request closed without merging**
