### PR TITLE
Adding Sowmya to the list

### PR DESCRIPTION
**Pull request by smiaa**

### CODE REVIEW

**Comment by datapythonista** [comment]
Thanks @smiaa, good job. Do you mind in a separate PR, move the `Mentoring new pandas contributors (team 2019)` title to the top of the file, replacing the `pandas-mentoring` title?

Thanks!

**Comment by smiaa** [comment]
Sure, will do it. It's fun to learn about git by these tasks.

Regards

**Comment by smiaa** [comment]
fixed conflicts and moved the "Mentoring new pandas contributors (team 2019)" title to the top of the file, replacing the "pandas-mentoring" title

**Comment by smiaa** [comment]
HI Marc,
I found, my pull request had conflicts and so wasn't merged. I have created
a new PR after resolving conflict and also have moved the title as you
instructed. It was bit confusing but I'm getting to understand git better
now.

Thanks
Sowmya

**Comment by datapythonista** [comment]
No worries, the goal of this is to be confused, and practice until things start to makes sense. I'll be explaining all the theory once everybody is done with the first task.

In case it makes things easier to understand now, a pull request is nothing more than a github page linking to a branch, with a description and comments. There is no problem in closing PRs and opening new ones, but this is usually not needed. Just updating the branch (the remote branch, pushing your local one) should be enough in most cases.

**Comment by smiaa** [comment]
Got it, Earlier I merged my branch with my master, in the two new PRs I
have created, I have kept them in separate branches and untouch my master.

**Pull request closed without merging**
