### PR TITLE
added myself to the list of people interested in contributing

### PR DESCRIPTION
**Pull request by MKhalusova**

### CODE REVIEW

**Comment by datapythonista** [comment]
Thanks @MKhalusova, good work.

Do you mind to remove my username from the list for now, in a separate pull request? It was more an example, and now we have other people. Thanks!

**Comment by MKhalusova** [comment]
Does it have to be a separate pull request?

**Comment by datapythonista** [comment]
Doing it in the same is very easy. Doing it in a separate PR is quite tricky, and you'll face some problems. I think you should learn several useful things by doing it in a separate one. So, that was my idea. :)

Btw, I see that something happened in this PR, and now it contains changes from PRs of other people. This happens very often to people contributing to pandas. Do you know which steps did you follow since you had just the first change in the PR? Thanks!

**Comment by MKhalusova** [comment]
I rebased onto the upstream and resolved conflicts :)

**Comment by datapythonista** [comment]
Was it?
```
git fetch upstream
git rebase -i
```

**Comment by MKhalusova** [comment]
I did it all through UI in PyCharm, so I'm not 100% of exact commands under the hood.

**Comment by datapythonista** [comment]
ah, that makes sense, thanks for the info, it's very useful

No idea about PyCharm, but if you want to update your branch with the latest changes in the repo, the best way is probably:
```
git fetch upstream
git merge upstream/master
```

**Comment by MKhalusova** [comment]
Sure, there are many ways of achieving the same result :)

**Comment by MKhalusova** [comment]
So... Just to clarify, is it good to merge and close the PR? or do you expect me to close this one and create a new separate PR?

**Comment by datapythonista** [comment]
Something went wrong with this PR, see the commit history: https://github.com/python-sprints/pandas-mentoring/pull/8/commits and also the diff, it's adding a logo file and other stuff that it's unrelated to what you want to change here.

Up to you if you want to fix it and open a separate one to remove my username from the list, or close this one and open two new ones for both changes.

**Comment by MKhalusova** [comment]
I'll close this one, and add start over. that'll be the fastest way

**Pull request closed without merging**
