### PR TITLE
Create about.rst

### PR DESCRIPTION
**Pull request by martinagvilas**
References to issue #119 

The headers are mostly based on the [about.rst of scikit learn](https://github.com/scikit-learn/scikit-learn/blob/master/doc/about.rst).

The style of the headers are based on the .rst already present in the `/doc/source/development/ ` folder of this repositiory.

### CODE REVIEW

**Review by datapythonista — COMMENTED** [review]
Good start. Couple of things.

I think referencing the scikit-learn page was a bit misleading, for now I'm not planning an "about us" section, but only a citing section for the paper citations and the logo.

Unrelated, there is a last minute change. Seems like the website will be using markdown instead of restructuredText, do you mind please changing this (and you can remove the label at the top).

Thanks for working on this!

**Comment by martinagvilas** [comment]
Sure! What about now?

**Comment by datapythonista** [comment]
Looks perfect now, thanks.

Sorry this is a bit abstract as a single page. I hope I can add the structure of the new website very soon, and things will become easier and clearer with all the context.

**Comment by martinagvilas** [comment]
Great! So no more changes are needed for this PR?

**Review by datapythonista — APPROVED** [review]
Feel free to merge it if you prefer to work step by step, but the final goal of the issue is to have these two sections populated.

**Comment by martinagvilas** [comment]
I will merge so that @WuraolaOyewusi and I can work together in this issue. But of course I won't close the issue until both sections are populated.

**Pull request merged**
