### PR TITLE
restructure markdown trail-1

### LINKED ISSUE #90: structuring the LEARNING_POINTS.md document
How about structuring it based on topics like git, environment setup etc? Or just listing it for now and grouping it at later point?

### PR DESCRIPTION
**Pull request by sara-02**
Fixes https://github.com/python-sprints/pandas-mentoring/issues/90

### CODE REVIEW

**Comment by sara-02** [comment]
@asvithajanani @WuraolaOyewusi PTAL.
This is how the file looks now.
Screenshot from 2019-08-13 20-49-49

**Comment by WuraolaOyewusi** [comment]
This looks tidier and well put together. @sara-02 
I like how added clear instructions. Thank you
Do you think we should still add the names? More people will be joining, do we want a lot of names?

**Comment by sara-02** [comment]
@WuraolaOyewusi at this point how else to differentiate the points between learners, we can either go the way of names or via topics learned.

**Comment by WuraolaOyewusi** [comment]
ok @sara-02 .I understand, We will keep the names

**Review by WuraolaOyewusi — APPROVED** [review]

**Review by dujm — APPROVED** [review]

**Pull request merged**
