### PR TITLE
Added MKhalusova to the list

### PR DESCRIPTION
**Pull request by MKhalusova**
Second pull request, new fork though.

### CODE REVIEW

**Comment by datapythonista** [comment]
do you mind doing the changes in separate PRs please?

**Comment by MKhalusova** [comment]
Ok, sure. This PR now only contains adding the user.

**Review by datapythonista — APPROVED** [review]
lgtm, thanks

will wait for the other one before I merge it

**Comment by datapythonista** [comment]
Thanks for the PRs, good job!

**Pull request merged**
