### PR TITLE
Add Name to Mentoring List

### PR DESCRIPTION
**Pull request by WuraolaOyewusi**

### CODE REVIEW

**Comment by datapythonista** [comment]
Thanks @WuraolaOyewusi, good job. We made changes to the repository (other people added their usernames) since you did the clone, and now your branch is outdated. You can update it with the last changes with:
```
git fetch upstream
git merge upstream/master
```

Note that you need to have the upstream remote defined for this to work (you only need to do it the first time, by `git remote add upstream git@github.com:python-sprints/pandas-mentoring.git`).

And also, note that when you do the merge, you'll have a conflict that you'll have to resolve (manually edit the file).

Let me know if you need help. Thanks!

**Comment by datapythonista** [comment]
Thanks for the update @WuraolaOyewusi. Looks like when fixing the conflict couple of lines of the file where accidentally removed. That's quite normal at the beginning, I'll show you some tricks later on (like doing a `git diff upstream/master` after you resolved the conflict). If you can have a look now, and fix it.

And don't worry if everything seems to go wrong, I'm intentionally causing that as much as I can, so you can learn about all these things. :)

**Comment by WuraolaOyewusi** [comment]
Ok Marc,
I will take a look at that.
Thank you

**Comment by WuraolaOyewusi** [comment]
Hi Marc,

I don't know how to fix this yet.

Do I need to do some form of 'reset'?

**Comment by datapythonista** [comment]
You can do a reset (there is a `git reset` that you could use), but for now if probably better to edit the file manually, and make the changes.

If you have a look here, you'll see that the initial description is deleted: https://github.com/python-sprints/pandas-mentoring/pull/16/files

Also, please add your username at the end.

After you push, you can go back to that link, and make sure that no content was changed, except for a single line with your username being added.

Does this make sense?

**Comment by WuraolaOyewusi** [comment]
Ok, It makes sense.

**Comment by WuraolaOyewusi** [comment]
Hi Marc,

I've edited the file manually.
No conflicts with base branch for now.

If I've finally gotten this right, I can attempt other tasks.

I'm learning, I'm glad I attempted this.
Thank you

**Comment by datapythonista** [comment]
Great job @WuraolaOyewusi. Just a little suggestion. After you create or update a PR, it's usually a good practice to looks at the files tab https://github.com/python-sprints/pandas-mentoring/pull/16/files and double check that the changes you're proposing are the ones you want to propose.

In this case you're introducing a blank line, that it's likely to cause a split of the list of participants in two. And I think we want a united team. ;)

After you change that, do you mind in a separate PR to create a new file `LEARNING_POINTS.md` (or whatever name you want), and start a list of the things you've learned? Once that other PR is merged, you can ask the rest of the team to add to the list what they've learned too (I guess many things will be the same, but others probably won't).

Thank you!

**Review by datapythonista — APPROVED** [review]
Looks great now. Will wait to merge until you create the other PR, but this is ready now. :)

**Comment by WuraolaOyewusi** [comment]
I  understand I will pay more attention to files tabs, they have been helpful and I have created the other PR.

**Comment by datapythonista** [comment]
In case it's not obvious, I'm doing all what I can to make those things fail, so you can learn those things (fixing conflicts, reviewing the diffs...) now, and in a friendly and very simply environment. Just saying to make sure that you don't feel like you had to know those beforehand. :)

**Comment by WuraolaOyewusi** [comment]
This has been an interesting way to learn. 
 I don't feel like I had to know them.

**Comment by datapythonista** [comment]
Thanks @WuraolaOyewusi, good job.

The main take away of this last part was to not use master directly to make changes, but keep it clean and always work in branches. 

See this comment here too: https://github.com/python-sprints/pandas-mentoring/pull/50#issuecomment-516847608

Let me know if you have questions.

**Pull request merged**
