### PR TITLE
username enfageorge is added

### PR DESCRIPTION
**Pull request by beingenfa**

### CODE REVIEW

**Review by dujm — APPROVED** [review]

**Comment by Aya-S** [comment]
hey @dujm !
is approving PRs related to them getting merged or is it only a review step?

**Comment by dujm** [comment]
Hi @Aya-S, good question ;) They are two steps. If I understand right, we should try to have two reviewers for each PR before merging it. That's why I only do the ```Merge``` when I'm the 2nd reviewer. 


But I could be wrong. What would you suggest, Marc? @datapythonista

**Comment by Aya-S** [comment]
@dujm I might be wrong but as far as I understand not everyone can merge PRs

**Comment by Aya-S** [comment]
@dujm I can't even find the to the option to approve or ask for changes open for me

**Comment by dujm** [comment]
@Aya-S  I think that's because you are not in the organization member list. (That's also one reason why we need to add our accounts in the```README```)  

Marc said we should be able to add each other. Let's try. If you could see this [member page](https://github.com/orgs/python-sprints/teams/pandas-mentoring/members), could you click ```Request to join``` on the top right?

**Comment by datapythonista** [comment]
Great team work here!

Regarding the approvals, it's a convention, and we can choose our own. The approval is just like a comment saying you're happy to get this merged, but it's more visible and easy to see. And also, github can be set up to allow only merged in PRs with more than N approvals.

If just want person is reviewing and merging it's quite easy that doesn't see something, and merges things that could be improved. I merged a PR adding a username with a typo, which wasn't rendering correctly previously. Having people approving things is great, we can decide how we want to work in this sense. May be someone can create an issue to discuss how many approvals do we want, and whether we want to require the approvals on the github settings, or we don't, in case we want to be flexible and allow exceptions.

Regarding the permissions, everybody should have permissions to merge eventually. I gave to few people already, and didn't give to the rest because didn't have the time. If the people with permissions can add the rest to the organization (not necessarily all at once), that would be good. Otherwise will check why not, and what I need to do so people have permission to do that.

**Comment by Aya-S** [comment]
@dujm  can't open the page :D 
@datapythonista  thanks for the clarification! We can take our time with this propagating merge permissions. we're still getting the hang of this. I will open the issue about the number of reviewers and review conventions.

**Comment by dujm** [comment]
Hi @enfageorge, there's a conflict in the ```README.md ```. Would you like to practice solving conflict from command line? Then I will merge your PR directly (no need to have a 2nd  review, I think).

**Comment by beingenfa** [comment]
@dujm is it okay now?

**Review by datapythonista — APPROVED** [review]
lgtm, thanks @enfageorge

**Comment by dujm** [comment]
@enfageorge Perfect, thanks!

**Pull request merged**
