### PR TITLE
add pandas documentation

### PR DESCRIPTION
**Pull request by sparalic**
Copy pandas documentation files (#12)

### CODE REVIEW

**Review by datapythonista — COMMENTED** [review]
Looks great, just two comments.

I think if you have in the first line of the PR description `Closes #12`, when we merge this, the issue will automatically close.

Then, I think it'd be useful for when we add other things to this repo, to have the same structure as in pandas for the directories. So, `pandas-documentation/` makes sense, but I'd probably use `doc/source/development`.

Other than that, looks perfect. Thanks!

**Comment by sparalic** [comment]
@datapythonista. Got it, I am closing this one and creating the updated PR with the correct file structure.

**Review by datapythonista — APPROVED** [review]
lgtm, thanks @sparalic 

I'll leave this open for a bit, so other people can have a look, comment... But will merge soon.

**Comment by datapythonista** [comment]
this seems to have the correct file structure now

**Pull request closed without merging**
