### PR TITLE
Resolved conflicts  & Moved Title

### PR DESCRIPTION
**Pull request by smiaa**
Resolved conflicts in my previous commit and moved the title

### CODE REVIEW

**Comment by datapythonista** [comment]
Thanks @smiaa, great job. But do you mind having both changes (your username and the title) in separate PRs first?

**Comment by smiaa** [comment]
ok closing this and opening two separate PRs

**Comment by datapythonista** [comment]
Just for your information, when you fix conflicts, you need to edit the conflicting file, and leave it in a correct state: remove the `<<<<<<`... that git adds to inform you what is conflicting, and leave the right lines of what's been updated. In this case you want to leave the line adding your username, and also the ones of people who added theirs since you started working in this branch.

**Comment by smiaa** [comment]
Thanks Marc, I have closed this PR and open two PRs one for adding my
username and another for the title change.  Please check and advice.

Regards
Sowmya

**Pull request closed without merging**
