### PR TITLE
Add montjoile to contributors list

### PR DESCRIPTION
**Pull request by montjoile**
Added username: montjoile

### CODE REVIEW

**Review by datapythonista — APPROVED** [review]
Thanks for the contribution @montjoile, good job.

Do you mind to change in a separate PR the footer from `This list is not yet complete—we'll keep adding more people.` to `This list is not yet complete - we will keep adding more people.` (note the spaces around the dash, and the `we will` instead of `we'll`. I think it'll look a bit better.

Thanks!

**Comment by montjoile** [comment]
I believe that I mistakenly pushed the changes in the same PR, should I create another one or is it fine like this?

**Comment by datapythonista** [comment]
You should create a new one. It's a bit tricky, and you should learn useful things when you do it. That's why I asked about those changes in the first place. :)

**Comment by datapythonista** [comment]
Thanks @montjoile, if this is superseded by #42, feel free to close it.

**Pull request closed without merging**
