### PR TITLE
add username Bhagya to README

### PR DESCRIPTION
**Pull request by BhagyaC**

### CODE REVIEW

**Review by datapythonista — APPROVED** [review]
Thanks @BhagyaC, great job. Do you mind in a new PR to create a file `SURVEY.md`, add couple of questions that you think we should add to the survey, and once it's merged, ask the rest of the team to submit PRs with their proposed questions?

Thanks!

**Comment by BhagyaC** [comment]
> Thanks @BhagyaC, great job. Do you mind in a new PR to create a file `SURVEY.md`, add couple of questions that you think we should add to the survey, and once it's merged, ask the rest of the team to submit PRs with their proposed questions?
> 
> Thanks!

@datapythonista , I have created a SURVEY.md and added some possible questions I'm not able to create a PR becuase of unfinished merges are there.

**Comment by datapythonista** [comment]
That was intended @BhagyaC, you (and everyone else or almost everyone else) created the first PR from master, which is not great for exactly this reason, you can't create a new branch and open a new PR, because you don't have a "clean" branch to start from.

You can have a look at this to see how you can move forward: https://github.com/python-sprints/pandas-mentoring/pull/14#issuecomment-516960921

**Comment by BhagyaC** [comment]
> That was intended @BhagyaC, you (and everyone else or almost everyone else) created the first PR from master, which is not great for exactly this reason, you can't create a new branch and open a new PR, because you don't have a "clean" branch to start from.
> 
> You can have a look at this to see how you can move forward: [#14 (comment)](https://github.com/python-sprints/pandas-mentoring/pull/14#issuecomment-516960921)

Yeah I got the Idea I have requested a new pull request from new branch. I will do the same for SURVEY.md

**Pull request closed without merging**
