### PR TITLE
Move title

### PR DESCRIPTION
**Pull request by smiaa**
This PR is to move title

### CODE REVIEW

**Comment by datapythonista** [comment]
Good job, looking good. Just one small thing.

I think you created this branch from the branch in which you added the name, and not from master.

To not get things mixed among branches, the best practice is probably to never commit anything to master, and to switch to master (i.e. `git checkout master`) before creating any branch.

Do you mind doing that, and in a new branch, and open another PR to move the title? Thanks!

**Comment by smiaa** [comment]
Sure would do that. Also I have a doubt, to update my master do I need to
do git pull from the remote master or git upstream commands you mentioned
in another thread?

**Comment by datapythonista** [comment]
Sorry, missed that question.

To update your local master what I'd do is:

```
git checkout master
git fetch upstream
git merge upstream/master
```

`git pull` is a shortcut for the last two commands, but I think there are small differences, but I don't remember the details, I'd have to check.

**Comment by datapythonista** [comment]
@smiaa I see you still have the username here, do you want to give a try to make the two changes independent?

**Comment by smiaa** [comment]
@datapythonista I am still working on fixing issues with my local master and local branch. I will try and get the title change separated. Resolve conflicts and commit again.

**Comment by smiaa** [comment]
@datapythonista  I have fixed the conflicts in the README and separated the title changes from username. Is this ok?

**Review by datapythonista — APPROVED** [review]
lgtm, thanks @smiaa 

I'll let someone else merge (we first approve and then someone else merges, so we have couple of reviewers for everything we merge)

**Pull request merged**
