### PR TITLE
Adding github username for Aya Salama

### PR DESCRIPTION
**Pull request by Aya-S**
Adding GitHub username for Aya Salama, Task 1 Mentoring Project

### CODE REVIEW

**Review by dujm — APPROVED** [review]

**Comment by datapythonista** [comment]
Thanks @Aya-S, great job.

Do you mind in a separate PR, to add at the end of the README file a section `Things we learned` (use any name you want for the title), and if you already learned something, add bullet points briefly explaining.

Thanks!

**Comment by Aya-S** [comment]
@datapythonista  there seems to be a merge conflict. should I fix it via the "Resolve conflicts" button above or through the command line via another PR?

**Comment by datapythonista** [comment]
I think for now it's better if you make it locally, you understand better the process. But up to you.

**Comment by datapythonista** [comment]
Do you mind adding the `things we learned` section in a separate PR? Thanks

**Comment by Aya-S** [comment]
Hi @datapythonista I'm not sure why were the changes automatically linked to this PR. when I tried to open a new PR I was lead to this older one because the new commits were already " automatically" linked here. was it because it was still open? or maybe because of the merge conflict?

**Comment by datapythonista** [comment]
There is something quite tricky going on, that's why I was forcing this error to happen. :)

A PR is nothing else than a fancy web page for a branch published in your remote branch. Doesn't really matter if they are open or close for this.

The problem here, is that when you create a new branch (e.g. `git checkout -b new_branch`), the branch is created from the active branch at that time. If that is always an unmodified `master` that is the same as the latest version of the original repository `master`, then everything works as you'd expect. But if you modify `master` (adding your username), and then you create a branch for it, your new branch will contain those changes with your username. Same if you create a branch from another branch.

The moral of the story is that if you want to work on independent changes, you need to always keep your `master` branch clean (without your own changes), updated, and always fork from `master`.

Does this make sense?

**Comment by Aya-S** [comment]
@datapythonista  yup, makes sense. 
will do some cleaning up and create a new branch from a clean master as things go unnecessarily messy already. I will actually refork and start clean and take care not to do edits on the local master branch.

**Comment by smiaa** [comment]
Aya, I had the same issue, you can do a pull request from upstream
(pandas-sprints/pandas-mentoring) to your local as well. And you can
approve it and it will update your master/branch whichever you wanted to
update. Please check this as well.

**Pull request closed without merging**
