### PR TITLE
Please share what you have learnt

### PR DESCRIPTION
**Pull request by WuraolaOyewusi**

### CODE REVIEW

**Comment by datapythonista** [comment]
Great job @WuraolaOyewusi. Did you see that you've also got the addition of the username in this PR? this should be only in the other. Can you have a look and let me know if you can't fix it?

Thanks!

**Comment by WuraolaOyewusi** [comment]
I don't know how to fix it yet. I thought creating a new branch will solve that. Let me check again

**Comment by datapythonista** [comment]
Can you update your branch?

```
git checkout learning
git fetch upstream
git merge upstream/master
```

Thanks!

**Comment by WuraolaOyewusi** [comment]
Hi Marc.
I read  #50 . Now that I understand what happens when changes are made from master and not a branch
Is there anything I can learn to fix it. I wouldn't want the same thing to happen to my other PRs

**Comment by datapythonista** [comment]
If you feel brave, things can be fixed with `git reset`, `git rebase` and probably others. But I wouldn't do that myself.

Given that your changes are small, I think you can save anything worth saving of what you did in a temporary place. Remove your whole repo, clone again, and create branches from master for every feature, and never change master directly. I think that's good enough for now, you'll have the opportunity to do more complex things with git in the future, but fixing messes in git is challenging even for very experienced people.

**Comment by WuraolaOyewusi** [comment]
I will start over. It is an opportunity to test my mastery of what I have been learning and doing.
When I create branches, do I need to merge them with my master?
I will read #50 again

**Comment by datapythonista** [comment]
Very good question. The answer is a bit tricky. Your branches, if the PR is merged, will be merged with your master. But you won't do that manually. What you will do instead is fetch all the changes in the original repository (including yours, but also all the ones from everyone else) and merge those.
```
git fetch upstream # this will download from the original repository all the code
git checkout master # make the master branch active, if it's not
git merge upstream/master # put all the changes you downloaded from the original repository into your local master
```

**Comment by WuraolaOyewusi** [comment]
Hi Marc,
I  started over and created a new PR  #67 , this time from a separate branch
Can I close this PR?
Thank you for the prompts

**Comment by datapythonista** [comment]
Yes, feel free to close your own PRs when they are not useful anymore.

**Pull request closed without merging**
