### PR TITLE
removed datapythonista from the list

### PR DESCRIPTION
**Pull request by MKhalusova**

### CODE REVIEW

**Comment by MKhalusova** [comment]
Separate PR for removing a user from the list

**Comment by datapythonista** [comment]
do you have two different copies of the repo?

**Comment by MKhalusova** [comment]
No, that's just a different branch

**Comment by datapythonista** [comment]
Ok, in general, when you make changes to master (like in your first PR), and you create a new branch after that, your new branch gets the changes in master. I was expecting here to see also your username added. Not sure if you create the branch first, or there is some pycharm magic going on, but the take away of the task was to avoid committing to master, and for every feature use a new different branch. :)

**Comment by MKhalusova** [comment]
Yeah, it's easy to forget about best practices, when it's a one-liner. Guilty as charged )

**Pull request merged**
